services:
  backend:
    image: ghcr.io/kritisans25/opsmonitor-backend:latest

    container_name: opsmonitor-backend

    env_file:
      - .env

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  frontend:
    image: ghcr.io/kritisans25/opsmonitor-frontend:latest

    container_name: opsmonitor-frontend

    ports:
      - "80:80"

    restart: unless-stopped

    depends_on:
      backend:
        condition: service_healthy